// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: wire.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED      Kind = 0
	Kind_KIND_HELLO            Kind = 1
	Kind_KIND_HELLO_ACK        Kind = 2
	Kind_KIND_RESOLVE_REQUEST  Kind = 3
	Kind_KIND_RESOLVE_RESPONSE Kind = 4
	Kind_KIND_CALL             Kind = 5
	Kind_KIND_SEND             Kind = 6
	Kind_KIND_RESPONSE         Kind = 7
	Kind_KIND_PING             Kind = 8
	Kind_KIND_PONG             Kind = 9
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HELLO",
		2: "KIND_HELLO_ACK",
		3: "KIND_RESOLVE_REQUEST",
		4: "KIND_RESOLVE_RESPONSE",
		5: "KIND_CALL",
		6: "KIND_SEND",
		7: "KIND_RESPONSE",
		8: "KIND_PING",
		9: "KIND_PONG",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":      0,
		"KIND_HELLO":            1,
		"KIND_HELLO_ACK":        2,
		"KIND_RESOLVE_REQUEST":  3,
		"KIND_RESOLVE_RESPONSE": 4,
		"KIND_CALL":             5,
		"KIND_SEND":             6,
		"KIND_RESPONSE":         7,
		"KIND_PING":             8,
		"KIND_PONG":             9,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_OK                     ErrorCode = 0
	ErrorCode_ERROR_CODE_REMOTE_UNAVAILABLE     ErrorCode = 1
	ErrorCode_ERROR_CODE_STALE_REF              ErrorCode = 2
	ErrorCode_ERROR_CODE_SERVICE_NOT_FOUND      ErrorCode = 3
	ErrorCode_ERROR_CODE_SERVICE_NOT_READY      ErrorCode = 4
	ErrorCode_ERROR_CODE_SERVICE_STOPPING       ErrorCode = 5
	ErrorCode_ERROR_CODE_PROTOCOL_NOT_FOUND     ErrorCode = 6
	ErrorCode_ERROR_CODE_PROTOCOL_TYPE_MISMATCH ErrorCode = 7
	ErrorCode_ERROR_CODE_CODEC                  ErrorCode = 8
	ErrorCode_ERROR_CODE_MAILBOX_TIMEOUT        ErrorCode = 9
	ErrorCode_ERROR_CODE_MAILBOX_FULL           ErrorCode = 10
	ErrorCode_ERROR_CODE_CALL_TIMEOUT           ErrorCode = 11
	ErrorCode_ERROR_CODE_CALL_CYCLE             ErrorCode = 12
	ErrorCode_ERROR_CODE_BACKPRESSURE           ErrorCode = 13
	ErrorCode_ERROR_CODE_HANDLER                ErrorCode = 14
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_OK",
		1:  "ERROR_CODE_REMOTE_UNAVAILABLE",
		2:  "ERROR_CODE_STALE_REF",
		3:  "ERROR_CODE_SERVICE_NOT_FOUND",
		4:  "ERROR_CODE_SERVICE_NOT_READY",
		5:  "ERROR_CODE_SERVICE_STOPPING",
		6:  "ERROR_CODE_PROTOCOL_NOT_FOUND",
		7:  "ERROR_CODE_PROTOCOL_TYPE_MISMATCH",
		8:  "ERROR_CODE_CODEC",
		9:  "ERROR_CODE_MAILBOX_TIMEOUT",
		10: "ERROR_CODE_MAILBOX_FULL",
		11: "ERROR_CODE_CALL_TIMEOUT",
		12: "ERROR_CODE_CALL_CYCLE",
		13: "ERROR_CODE_BACKPRESSURE",
		14: "ERROR_CODE_HANDLER",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_OK":                     0,
		"ERROR_CODE_REMOTE_UNAVAILABLE":     1,
		"ERROR_CODE_STALE_REF":              2,
		"ERROR_CODE_SERVICE_NOT_FOUND":      3,
		"ERROR_CODE_SERVICE_NOT_READY":      4,
		"ERROR_CODE_SERVICE_STOPPING":       5,
		"ERROR_CODE_PROTOCOL_NOT_FOUND":     6,
		"ERROR_CODE_PROTOCOL_TYPE_MISMATCH": 7,
		"ERROR_CODE_CODEC":                  8,
		"ERROR_CODE_MAILBOX_TIMEOUT":        9,
		"ERROR_CODE_MAILBOX_FULL":           10,
		"ERROR_CODE_CALL_TIMEOUT":           11,
		"ERROR_CODE_CALL_CYCLE":             12,
		"ERROR_CODE_BACKPRESSURE":           13,
		"ERROR_CODE_HANDLER":                14,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Incarnation   string                 `protobuf:"bytes,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Address       uint64                 `protobuf:"varint,4,opt,name=address,proto3" json:"address,omitempty"`
	Generation    uint64                 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Target) GetIncarnation() string {
	if x != nil {
		return x.Incarnation
	}
	return ""
}

func (x *Target) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Target) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Target) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type CallFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallFrame) Reset() {
	*x = CallFrame{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallFrame) ProtoMessage() {}

func (x *CallFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallFrame.ProtoReflect.Descriptor instead.
func (*CallFrame) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *CallFrame) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CallFrame) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CallFrame) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type RemoteError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=skygo.cluster.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteError) Reset() {
	*x = RemoteError{}
	mi := &file_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteError) ProtoMessage() {}

func (x *RemoteError) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteError.ProtoReflect.Descriptor instead.
func (*RemoteError) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_OK
}

func (x *RemoteError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Envelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Kind               Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=skygo.cluster.v1.Kind" json:"kind,omitempty"`
	RequestId          uint64                 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SourceNode         string                 `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	Incarnation        string                 `protobuf:"bytes,5,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	TimestampUnixMilli int64                  `protobuf:"varint,6,opt,name=timestamp_unix_milli,json=timestampUnixMilli,proto3" json:"timestamp_unix_milli,omitempty"`
	Nonce              []byte                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Mac                []byte                 `protobuf:"bytes,8,opt,name=mac,proto3" json:"mac,omitempty"`
	Target             *Target                `protobuf:"bytes,9,opt,name=target,proto3" json:"target,omitempty"`
	Service            string                 `protobuf:"bytes,10,opt,name=service,proto3" json:"service,omitempty"`
	Protocol           string                 `protobuf:"bytes,11,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Fingerprint        string                 `protobuf:"bytes,12,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	DeadlineUnixNano   int64                  `protobuf:"varint,13,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`
	CallPath           []*CallFrame           `protobuf:"bytes,14,rep,name=call_path,json=callPath,proto3" json:"call_path,omitempty"`
	Payload            []byte                 `protobuf:"bytes,15,opt,name=payload,proto3" json:"payload,omitempty"`
	Error              *RemoteError           `protobuf:"bytes,16,opt,name=error,proto3" json:"error,omitempty"`
	TraceId            string                 `protobuf:"bytes,17,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *Envelope) GetIncarnation() string {
	if x != nil {
		return x.Incarnation
	}
	return ""
}

func (x *Envelope) GetTimestampUnixMilli() int64 {
	if x != nil {
		return x.TimestampUnixMilli
	}
	return 0
}

func (x *Envelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Envelope) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *Envelope) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Envelope) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Envelope) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Envelope) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Envelope) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

func (x *Envelope) GetCallPath() []*CallFrame {
	if x != nil {
		return x.CallPath
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetError() *RemoteError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\x10skygo.cluster.v1\"\x92\x01\n" +
	"\x06Target\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12 \n" +
	"\vincarnation\x18\x02 \x01(\tR\vincarnation\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\x04R\aaddress\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x04R\n" +
	"generation\"U\n" +
	"\tCallFrame\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"X\n" +
	"\vRemoteError\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.skygo.cluster.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe8\x04\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.skygo.cluster.v1.KindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vsource_node\x18\x04 \x01(\tR\n" +
	"sourceNode\x12 \n" +
	"\vincarnation\x18\x05 \x01(\tR\vincarnation\x120\n" +
	"\x14timestamp_unix_milli\x18\x06 \x01(\x03R\x12timestampUnixMilli\x12\x14\n" +
	"\x05nonce\x18\a \x01(\fR\x05nonce\x12\x10\n" +
	"\x03mac\x18\b \x01(\fR\x03mac\x120\n" +
	"\x06target\x18\t \x01(\v2\x18.skygo.cluster.v1.TargetR\x06target\x12\x18\n" +
	"\aservice\x18\n" +
	" \x01(\tR\aservice\x12\x1a\n" +
	"\bprotocol\x18\v \x01(\tR\bprotocol\x12 \n" +
	"\vfingerprint\x18\f \x01(\tR\vfingerprint\x12,\n" +
	"\x12deadline_unix_nano\x18\r \x01(\x03R\x10deadlineUnixNano\x128\n" +
	"\tcall_path\x18\x0e \x03(\v2\x1b.skygo.cluster.v1.CallFrameR\bcallPath\x12\x18\n" +
	"\apayload\x18\x0f \x01(\fR\apayload\x123\n" +
	"\x05error\x18\x10 \x01(\v2\x1d.skygo.cluster.v1.RemoteErrorR\x05error\x12\x19\n" +
	"\btrace_id\x18\x11 \x01(\tR\atraceId*\xc4\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\x12\n" +
	"\x0eKIND_HELLO_ACK\x10\x02\x12\x18\n" +
	"\x14KIND_RESOLVE_REQUEST\x10\x03\x12\x19\n" +
	"\x15KIND_RESOLVE_RESPONSE\x10\x04\x12\r\n" +
	"\tKIND_CALL\x10\x05\x12\r\n" +
	"\tKIND_SEND\x10\x06\x12\x11\n" +
	"\rKIND_RESPONSE\x10\a\x12\r\n" +
	"\tKIND_PING\x10\b\x12\r\n" +
	"\tKIND_PONG\x10\t*\xca\x03\n" +
	"\tErrorCode\x12\x11\n" +
	"\rERROR_CODE_OK\x10\x00\x12!\n" +
	"\x1dERROR_CODE_REMOTE_UNAVAILABLE\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_STALE_REF\x10\x02\x12 \n" +
	"\x1cERROR_CODE_SERVICE_NOT_FOUND\x10\x03\x12 \n" +
	"\x1cERROR_CODE_SERVICE_NOT_READY\x10\x04\x12\x1f\n" +
	"\x1bERROR_CODE_SERVICE_STOPPING\x10\x05\x12!\n" +
	"\x1dERROR_CODE_PROTOCOL_NOT_FOUND\x10\x06\x12%\n" +
	"!ERROR_CODE_PROTOCOL_TYPE_MISMATCH\x10\a\x12\x14\n" +
	"\x10ERROR_CODE_CODEC\x10\b\x12\x1e\n" +
	"\x1aERROR_CODE_MAILBOX_TIMEOUT\x10\t\x12\x1b\n" +
	"\x17ERROR_CODE_MAILBOX_FULL\x10\n" +
	"\x12\x1b\n" +
	"\x17ERROR_CODE_CALL_TIMEOUT\x10\v\x12\x19\n" +
	"\x15ERROR_CODE_CALL_CYCLE\x10\f\x12\x1b\n" +
	"\x17ERROR_CODE_BACKPRESSURE\x10\r\x12\x16\n" +
	"\x12ERROR_CODE_HANDLER\x10\x0eB8Z6github.com/scott4game/skygo/cluster/internal/wire;wireb\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wire_proto_goTypes = []any{
	(Kind)(0),           // 0: skygo.cluster.v1.Kind
	(ErrorCode)(0),      // 1: skygo.cluster.v1.ErrorCode
	(*Target)(nil),      // 2: skygo.cluster.v1.Target
	(*CallFrame)(nil),   // 3: skygo.cluster.v1.CallFrame
	(*RemoteError)(nil), // 4: skygo.cluster.v1.RemoteError
	(*Envelope)(nil),    // 5: skygo.cluster.v1.Envelope
}
var file_wire_proto_depIdxs = []int32{
	1, // 0: skygo.cluster.v1.RemoteError.code:type_name -> skygo.cluster.v1.ErrorCode
	0, // 1: skygo.cluster.v1.Envelope.kind:type_name -> skygo.cluster.v1.Kind
	2, // 2: skygo.cluster.v1.Envelope.target:type_name -> skygo.cluster.v1.Target
	3, // 3: skygo.cluster.v1.Envelope.call_path:type_name -> skygo.cluster.v1.CallFrame
	4, // 4: skygo.cluster.v1.Envelope.error:type_name -> skygo.cluster.v1.RemoteError
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		EnumInfos:         file_wire_proto_enumTypes,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
